### ISSUE TITLE
support non-UTF8 ucum-essence.xml

### ISSUE THREAD

**Issue by bartdecu** [BertVerhees/ucum#1]
Hi, 

I saw that you modified the ucum-essence.xml from unitsofmeasure.org to make it work (you removed the encoding line).

If you add a parameter to UnmarshalTerminology in DefinitionParser.go and GetInstanceOfUcumEssenceService in Ucum.go, you can fix this.

This parameter should be of type 

func(charset string, input io.Reader) (io.Reader, error)

and create a wrapper around the incoming reader that converts the encoding to UTF8.

Then, in UnmarshalTerminology, you should set decoder.CharsetReader to this parameter.

In that way, your API will support XML-files of any encoding, if the user provides the conversion function.

see https://github.com/golang/go/issues/8937 for a more profound explanation of the problem.

**Comment by BertVerhees** [comment]
Thanks, I'll see to it next week

**Comment by BertVerhees** [comment]
There seems to be a problem with the UCUM website. I check this issue as soon as that website is running again.

**Comment by BertVerhees** [comment]
The UCUM site is running again. I repaired the code so, that it reads the XML-file published there without any problem. ( http://unitsofmeasure.org/ucum-essence.xml )
If there in the future will be a encoding-line added, then I will add encoding-parsing to this project.
